# Generated by Django 4.2.1 on 2023-06-03 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_remove_ordervehicle_vehicle_alter_vehicle_car_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_updated_date',
            field=models.DateField(default=datetime.date(2023, 6, 3)),
        ),
    ]
