# Generated by Django 4.2.1 on 2023-07-03 00:11

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_labgroupmember_alter_ordervehicle_order_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CRUISE_CONTROL', 'Cruise Control'), ('AUDIO_INTERFACE', 'Audio Interface'), ('AIRBAGS', 'Airbags'), ('AIR_CONDITIONING', 'Air Conditioning'), ('SEAT_HEATING', 'Seat Heating'), ('PARK_ASSIST', 'ParkAssist'), ('POWER_STEERING', 'Power Steering'), ('REVERSING_CAMERA', 'Reversing Camera'), ('AUTO_START_STOP', 'Auto Start/Stop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_updated_date',
            field=models.DateField(default=datetime.date(2023, 7, 3)),
        ),
    ]
